import { api, getToken, setToken, connectSocket, escapeHtml } from './api.js';
import { t } from './i18n.js';

const state={user:null,teams:[],matches:[],joinRequests:[],history:{stats:{},participated:[],organized:[]},externalProfiles:[],providerCapabilities:{},profileSettings:null,openMatchId:null,socket:null,search:''};
const $=selector=>document.querySelector(selector);
const $$=selector=>[...document.querySelectorAll(selector)];
const inviteToken=new URLSearchParams(location.search).get('invite')||'';
function statusLabel(value){return String(value||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());}
function formatDate(value){if(!value)return 'Not set';const date=new Date(value);return Number.isNaN(date.getTime())?String(value):date.toLocaleString();}
function toast(message,error=false){const el=$('#ops-toast');el.textContent=message;el.classList.toggle('error',error);el.classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.add('hidden'),4200);}
function openExternal(url){if(url)window.open(url,'_blank','noopener,noreferrer');}
function showAuth(){$('#portal-auth').classList.remove('hidden');$('#portal-view').classList.add('hidden');$('#portal-logout').classList.add('hidden');window.GSGlobalMenu?.refresh();$('#invite-notice').textContent=inviteToken?'Sign in or register with the invited account, then accept the Captain invitation.':'';}
function showPortal(){$('#portal-auth').classList.add('hidden');$('#portal-view').classList.remove('hidden');$('#portal-logout').classList.add('hidden');window.GSGlobalMenu?.refresh();}
async function downloadFile(fileId,fileName='attachment'){try{const response=await fetch(`/api/files/${fileId}`,{credentials:'same-origin'});if(!response.ok){const payload=await response.json().catch(()=>({}));throw new Error(payload.error||`Download failed (${response.status})`);}const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=fileName;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(error){toast(error.message,true);}}
function readFileBase64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});}

async function bootstrap(){bindStatic();const params=new URLSearchParams(location.search);const startggStatus=params.get('startgg');const challongeStatus=params.get('challonge');if(startggStatus==='connected')toast(t('startggConnectedToast'));else if(startggStatus==='error')toast(t('startggConnectionFailedToast'),true);if(challongeStatus==='connected')toast(t('challongeConnectedToast'));else if(challongeStatus==='error')toast(t('challongeConnectionFailedToast'),true);if(!getToken())return showAuth();try{state.user=(await api('/api/auth/me')).user;showPortal();connectRealtime();await loadPortal();}catch(error){setToken('');showAuth();toast(error.message,true);}}
function bindStatic(){
  $('#portal-login-form').addEventListener('submit',async event=>{event.preventDefault();try{const payload=await api('/api/auth/login',{method:'POST',body:{identity:$('#portal-login-identity').value,password:$('#portal-login-password').value}});setToken('cookie-session');state.user=payload.user;showPortal();connectRealtime();await loadPortal();}catch(error){toast(error.message,true);}});
  $('#portal-register-form').addEventListener('submit',async event=>{event.preventDefault();try{const payload=await api('/api/auth/register',{method:'POST',body:{displayName:$('#portal-register-display').value,username:$('#portal-register-username').value,email:$('#portal-register-email').value,password:$('#portal-register-password').value,role:'player'}});setToken('cookie-session');state.user=payload.user;showPortal();connectRealtime();await loadPortal();}catch(error){toast(error.message,true);}});
  $('#portal-logout').addEventListener('click',()=>{setToken('');state.socket?.disconnect();state.user=null;showAuth();});
  $('#portal-refresh').addEventListener('click',loadPortal);
  $('#portal-search').addEventListener('input',event=>{state.search=event.target.value;renderMatches();});
  $('#portal-close-match').addEventListener('click',closeMatch);
  $('#portal-match-modal').addEventListener('click',event=>{if(event.target.id==='portal-match-modal')closeMatch();});
}
function connectRealtime(){state.socket?.disconnect();state.socket=connectSocket();if(!state.socket)return;state.socket.on('match:chat',payload=>{if(Number(payload.matchId)===state.openMatchId)appendChat(payload.message);});state.socket.on('bracket:updated',()=>loadPortal({quiet:true}));state.socket.on('match:updated',()=>loadPortal({quiet:true}));state.socket.on('match:checkin',async payload=>{const openMatchId=state.openMatchId;await loadPortal({quiet:true});if(openMatchId===Number(payload?.matchId))openMatch(openMatchId);});}
async function loadPortal({quiet=false}={}){try{const [payload,profilePayload,settingsPayload]=await Promise.all([api('/api/portal'),api('/api/profile/external'),api('/api/profile/settings')]);state.user=payload.user;state.teams=payload.teams;state.matches=payload.matches;state.joinRequests=payload.joinRequests||[];state.history=payload.history||{stats:{},participated:[],organized:[]};state.externalProfiles=profilePayload.profiles||[];state.providerCapabilities=profilePayload.providers||{};state.profileSettings=settingsPayload.profile||null;showPortal();[...new Set(state.teams.map(team=>team.tournament_id))].forEach(tournamentId=>state.socket?.emit('tournament:join',{tournamentId}));renderInvite();renderAccountSettings();renderAccountConnections();renderHistory();renderTeams();renderMatches();}catch(error){if(!quiet)toast(error.message,true);}}

function renderAccountSettings(){
  const profile=state.profileSettings||{};
  $('#portal-profile-display-name').value=profile.displayName||state.user.displayName||'';
  $('#portal-profile-gamer-tag').value=profile.gamerTag||'';
  $('#portal-profile-bio').value=profile.bio||'';
  $('#portal-profile-visibility').value=profile.profileVisibility==='private'?'private':'public';
  $('#portal-show-external-profiles').checked=Boolean(profile.showExternalProfiles);
  $('#portal-view-profile').href=`/profile.html?user=${encodeURIComponent(profile.username||state.user.username)}`;
  $('#portal-profile-settings-form').onsubmit=async event=>{event.preventDefault();try{const payload=await api('/api/profile/settings',{method:'PATCH',body:{displayName:$('#portal-profile-display-name').value,gamerTag:$('#portal-profile-gamer-tag').value,bio:$('#portal-profile-bio').value,profileVisibility:$('#portal-profile-visibility').value,showExternalProfiles:$('#portal-show-external-profiles').checked}});state.profileSettings=payload.profile;state.user.displayName=payload.profile.displayName;showPortal();toast(t('profileSettingsSaved'));}catch(error){toast(error.message,true);}};
  $('#portal-change-email-form').onsubmit=async event=>{event.preventDefault();try{await api('/api/auth/change-email/request',{method:'POST',body:{currentPassword:$('#portal-email-current-password').value,newEmail:$('#portal-new-email').value}});$('#portal-email-confirm-row').classList.remove('hidden');$('#portal-email-change-code').focus();toast(t('emailChangeCodeSent'));}catch(error){toast(error.message,true);}};
  $('#portal-confirm-email-change').onclick=async()=>{try{const payload=await api('/api/auth/change-email/confirm',{method:'POST',body:{code:$('#portal-email-change-code').value}});state.user=payload.user;state.profileSettings=payload.profile;$('#portal-email-confirm-row').classList.add('hidden');$('#portal-change-email-form').reset();toast(t('emailChangedToast'));await loadPortal({quiet:true});}catch(error){toast(error.message,true);}};
  $('#portal-change-password-form').onsubmit=async event=>{event.preventDefault();const next=$('#portal-password-new').value;if(next!==$('#portal-password-confirm').value)return toast(t('passwordConfirmationMismatch'),true);try{await api('/api/auth/change-password',{method:'POST',body:{currentPassword:$('#portal-password-current').value,newPassword:next}});event.currentTarget.reset();toast(t('passwordChangedToast'));}catch(error){toast(error.message,true);}};
}

function providerIdentity(profile){
  if(!profile)return '';
  if(profile.gamerTag||profile.displayName)return profile.gamerTag||profile.displayName;
  try{
    const url=new URL(profile.profileUrl);
    const parts=url.pathname.split('/').filter(Boolean);
    return decodeURIComponent(parts.at(-1)||profile.profileUrl);
  }catch{return profile.profileUrl||'';}
}
function renderAccountConnections(){
  const emailBox=$('#portal-email-verification');
  if(state.user.emailVerified){
    emailBox.innerHTML=`<div class="join-account-status approved"><span>${escapeHtml(t('emailVerifiedBadge'))}</span><h4>${escapeHtml(state.user.email)}</h4><p>${escapeHtml(t('emailVerifiedAccessDesc'))}</p></div>`;
  }else{
    emailBox.innerHTML=`<div class="join-account-status pending"><span>${escapeHtml(t('emailVerificationRequiredBadge'))}</span><h4>${escapeHtml(state.user.email)}</h4><p>${escapeHtml(t('emailVerificationPortalDesc'))}</p><form id="portal-verify-email-form" class="ops-toolbar"><input id="portal-email-code" inputmode="numeric" maxlength="6" pattern="[0-9]{6}" placeholder="${escapeHtml(t('sixDigitCodePlaceholder'))}" required><button class="btn btn-primary btn-sm">${escapeHtml(t('verifyEmailAction'))}</button><button class="btn btn-ghost btn-sm" id="portal-resend-email" type="button">${escapeHtml(t('resendCode'))}</button></form></div>`;
    $('#portal-verify-email-form')?.addEventListener('submit',async event=>{event.preventDefault();try{const payload=await api('/api/auth/verify-email',{method:'POST',body:{code:$('#portal-email-code').value}});state.user=payload.user;toast(t('emailVerifiedToast'));await loadPortal({quiet:true});}catch(error){toast(error.message,true);}});
    $('#portal-resend-email')?.addEventListener('click',async()=>{try{await api('/api/auth/resend-verification',{method:'POST'});toast(t('newVerificationCodeSent'));}catch(error){toast(error.message,true);}});
  }

  const profiles=new Map(state.externalProfiles.map(profile=>[profile.provider,profile]));
  const formDisabled=state.user.emailVerified?'':'disabled';
  const statusBadge=profile=>{
    if(!profile)return `<span class="portal-provider-status is-empty">${escapeHtml(t('actionRequired'))}</span>`;
    const verified=profile.verificationStatus==='verified';
    return `<span class="portal-provider-status ${verified?'is-verified':'is-review'}">${escapeHtml(verified?t('profileStatusVerified'):t('profileStatusNeedsReview'))}</span>`;
  };
  const currentProfile=profile=>profile?`<a class="portal-provider-current" href="${escapeHtml(profile.profileUrl)}" target="_blank" rel="noopener noreferrer"><span>${escapeHtml(providerIdentity(profile))}</span><small>${escapeHtml(profile.profileUrl)}</small><b aria-hidden="true">↗</b></a>`:'';
  const oauthButton=(provider,label,profile,kind='primary')=>`<button class="btn btn-${kind} btn-sm" type="button" data-connect-provider="${provider}" ${formDisabled}>${escapeHtml(profile?t('relinkProvider',{provider:label}):t('connectProvider',{provider:label}))}</button>`;
  const disconnectButton=provider=>`<button class="btn btn-danger btn-sm" type="button" data-disconnect-provider="${provider}">${escapeHtml(t('disconnect'))}</button>`;

  const startgg=profiles.get('startgg');
  const startggCard=`<article class="ops-form-card portal-provider-card portal-provider-card--startgg">
    <div class="portal-provider-main">
      <header class="portal-provider-head"><div class="portal-provider-brand"><span class="portal-provider-mark">S</span><div><b>start.gg</b><small>${escapeHtml(t('startggConnectDesc'))}</small></div></div>${statusBadge(startgg)}</header>
      ${currentProfile(startgg)}
    </div>
    <div class="portal-provider-actions">${startgg?`<a class="btn btn-ghost btn-sm" href="${escapeHtml(startgg.profileUrl)}" target="_blank" rel="noopener noreferrer">${escapeHtml(t('openProfileExternal'))}</a>`:''}${oauthButton('startgg','start.gg',startgg)}${startgg?disconnectButton('startgg'):''}</div>
  </article>`;

  const manualCard=(provider,label,profile,description,{oauth=false}={})=>`<form class="ops-form-card portal-provider-card portal-provider-card--manual portal-provider-card--${provider}" data-manual-provider="${provider}">
    <header class="portal-provider-head"><div class="portal-provider-brand"><span class="portal-provider-mark">${escapeHtml(label.slice(0,1).toUpperCase())}</span><div><b>${escapeHtml(label)}</b><small>${escapeHtml(description)}</small></div></div>${statusBadge(profile)}</header>
    ${currentProfile(profile)}
    ${profile&&profile.verificationStatus!=='verified'?`<div class="portal-provider-review-note">${escapeHtml(t('manualProfileHostReview'))}</div>`:''}
    <div class="portal-provider-fields">
      <label><span>${escapeHtml(t('profileUrlPlaceholder'))}</span><input name="profileUrl" type="url" value="${escapeHtml(profile?.profileUrl||'')}" placeholder="${escapeHtml(t('profileUrlPlaceholder'))}" required ${formDisabled}></label>
      <label><span>${escapeHtml(t('profileDisplayNamePlaceholder'))}</span><input name="displayName" value="${escapeHtml(profile?.displayName||profile?.gamerTag||'')}" placeholder="${escapeHtml(t('profileDisplayNamePlaceholder'))}" ${formDisabled}></label>
    </div>
    <div class="portal-provider-actions">${profile?`<a class="btn btn-ghost btn-sm" href="${escapeHtml(profile.profileUrl)}" target="_blank" rel="noopener noreferrer">${escapeHtml(t('openProfileExternal'))}</a>`:''}${oauth?oauthButton(provider,label,profile,'ghost'):''}<button class="btn btn-primary btn-sm" ${formDisabled}>${escapeHtml(profile?t('updateProfileLink'):t('saveProfile'))}</button>${profile?disconnectButton(provider):''}</div>
  </form>`;

  const tonamel=profiles.get('tonamel');
  const challonge=profiles.get('challonge');
  const challongeOAuth=Boolean(state.providerCapabilities?.challonge?.oauth);
  const tonamelCard=manualCard('tonamel','Tonamel',tonamel,t('tonamelManualProfileDesc'));
  const challongeCard=challonge?.verificationStatus==='verified'&&challongeOAuth
    ? `<article class="ops-form-card portal-provider-card portal-provider-card--manual portal-provider-card--challonge"><header class="portal-provider-head"><div class="portal-provider-brand"><span class="portal-provider-mark">C</span><div><b>Challonge</b><small>${escapeHtml(t('challongeOAuthDesc'))}</small></div></div>${statusBadge(challonge)}</header>${currentProfile(challonge)}<div class="portal-provider-actions"><a class="btn btn-ghost btn-sm" href="${escapeHtml(challonge.profileUrl)}" target="_blank" rel="noopener noreferrer">${escapeHtml(t('openProfileExternal'))}</a>${oauthButton('challonge','Challonge',challonge)}${disconnectButton('challonge')}</div></article>`
    : manualCard('challonge','Challonge',challonge,challongeOAuth?t('challongeOAuthDesc'):t('challongeManualProfileDesc'),{oauth:challongeOAuth});

  $('#portal-external-profiles').innerHTML=startggCard+tonamelCard+challongeCard;
  document.querySelectorAll('[data-connect-provider]').forEach(button=>button.addEventListener('click',()=>{location.href=`/api/connections/${button.dataset.connectProvider}?return=${encodeURIComponent('/portal.html')}`;}));
  document.querySelectorAll('[data-disconnect-provider]').forEach(button=>button.addEventListener('click',async()=>{const provider=button.dataset.disconnectProvider;if(!confirm(t('disconnectProviderConfirm',{provider})))return;try{await api(`/api/profile/external/${provider}`,{method:'DELETE'});toast(t('profileDisconnectedToast'));await loadPortal({quiet:true});}catch(error){toast(error.message,true);}}));
  document.querySelectorAll('[data-manual-provider]').forEach(form=>form.addEventListener('submit',async event=>{event.preventDefault();try{const data=new FormData(form);await api('/api/profile/external/manual',{method:'POST',body:{provider:form.dataset.manualProvider,profileUrl:data.get('profileUrl'),displayName:data.get('displayName')}});toast(t('profileSavedReviewToast'));await loadPortal({quiet:true});}catch(error){toast(error.message,true);}}));
}

function renderHistory(){
  const history=state.history||{stats:{},participated:[],organized:[]};const stats=history.stats||{};
  $('#portal-history-stats').innerHTML=`<div class="ops-stat"><div class="ops-stat-value">${Number(stats.participatedCount||0)}</div><div class="ops-stat-label">Events Played</div></div><div class="ops-stat"><div class="ops-stat-value">${Number(stats.championships||0)}</div><div class="ops-stat-label">Championships</div></div><div class="ops-stat"><div class="ops-stat-value">${Number(stats.podiums||0)}</div><div class="ops-stat-label">Top Finishes</div></div><div class="ops-stat"><div class="ops-stat-value">${Number(stats.organizedCount||0)}</div><div class="ops-stat-label">Events Organized</div></div>`;
  $('#portal-participated-history').innerHTML=(history.participated||[]).length?(history.participated||[]).map(item=>`<a class="portal-history-card achievement-${escapeHtml(item.achievement?.tone||'neutral')}" href="/public.html?slug=${encodeURIComponent(item.tournamentSlug)}" target="_blank" rel="noopener"><div><b>${escapeHtml(item.tournamentName)}</b><span>${escapeHtml(item.teamName)}${item.isCaptain?' · Captain':''}</span></div><div class="portal-achievement"><strong>${escapeHtml(item.achievement?.label||'Participant')}</strong><span>${escapeHtml(statusLabel(item.status))}</span></div></a>`).join(''):'<div class="portal-empty">No tournament participation recorded yet.</div>';
  $('#portal-organized-history').innerHTML=(history.organized||[]).length?(history.organized||[]).map(item=>`<a class="portal-history-card" href="/dashboard.html?tournamentId=${item.tournamentId}" target="_blank" rel="noopener"><div><b>${escapeHtml(item.tournamentName)}</b><span>${Number(item.teamCount||0)} teams · ${Number(item.matchCount||0)} matches</span></div><div class="portal-achievement"><strong>${escapeHtml(statusLabel(item.status))}</strong><span>${escapeHtml(formatDate(item.startAt||item.createdAt))}</span></div></a>`).join(''):'<div class="portal-empty">No organized tournaments recorded yet.</div>';
}

function renderInvite(){const panel=$('#portal-invite-action');if(!inviteToken){panel.classList.add('hidden');return;}panel.classList.remove('hidden');panel.innerHTML=`<div class="ops-section-header"><div><h3>Captain Invitation</h3><div class="ops-list-meta">Accepting links this account to the team as its official Captain.</div></div><button class="btn btn-primary" id="accept-invite">ACCEPT INVITATION</button></div>`;$('#accept-invite').addEventListener('click',async()=>{try{await api('/api/team-invitations/accept',{method:'POST',body:{token:inviteToken}});history.replaceState({},'',location.pathname);toast('Captain invitation accepted.');await loadPortal();}catch(error){toast(error.message,true);}});}
function renderTeams(){const pending=state.joinRequests.filter(item=>item.status==='pending');$('#portal-teams').innerHTML=state.teams.length?state.teams.map(team=>`<div class="ops-stat portal-team-card"><div class="ops-stat-value">${escapeHtml(team.tag)}</div><div class="ops-stat-label">${escapeHtml(team.name)}</div><div class="ops-list-meta">${escapeHtml(team.tournament_name)} · ${escapeHtml(statusLabel(team.my_member_role||'player'))}${team.my_is_captain?' · Captain access':''}${team.roster_locked_at?' · Roster locked':''}</div></div>`).join(''):`<div class="ops-section portal-empty">No team is linked to this account yet.${pending.length?` ${pending.length} join request(s) are waiting for Host confirmation.`:' Use JOIN / LINK ACCOUNT on a public tournament page.'}</div>`;}
function myTeamForMatch(match){return state.teams.find(team=>team.id===match.team_a_id||team.id===match.team_b_id)||null;}
function renderMatches(){const term=state.search.trim().toLowerCase();const matches=state.matches.filter(match=>!term||`${match.tournament_name} ${match.team_a_name} ${match.team_b_name} ${match.round_name}`.toLowerCase().includes(term));$('#portal-matches').innerHTML=matches.length?matches.map(match=>{const own=myTeamForMatch(match);const opponent=match.team_a_id===own?.id?match.team_b_name:match.team_a_name;return `<article class="portal-match-card" data-match-id="${match.id}"><div class="ops-kicker">${escapeHtml(match.tournament_name)} · ${escapeHtml(match.round_name||match.stage)}</div><div class="portal-versus"><span>${escapeHtml(match.team_a_name||'TBD')}</span><b>VS</b><span>${escapeHtml(match.team_b_name||'TBD')}</span></div><div class="portal-match-meta"><span>Your team: ${escapeHtml(own?.tag||'—')}</span><span>Opponent: ${escapeHtml(opponent||'TBD')}</span><span>BO${match.best_of}</span><span>${escapeHtml(statusLabel(match.result_status))}</span></div><div class="portal-match-meta" style="margin-top:7px"><span>${escapeHtml(formatDate(match.effective_scheduled_at))}</span>${match.stream_url?'<span class="ops-live-badge">EXTERNAL STREAM ↗</span>':''}</div></article>`;}).join(''):'<div class="portal-empty">No matches found.</div>';$$('.portal-match-card').forEach(card=>card.addEventListener('click',()=>openMatch(Number(card.dataset.matchId))));}
function closeMatch(){state.openMatchId=null;$('#portal-match-modal').classList.add('hidden');$('#portal-match-body').innerHTML='';}
async function openMatch(matchId){const match=state.matches.find(item=>item.id===matchId);if(!match)return;state.openMatchId=matchId;$('#portal-match-round').textContent=`${match.tournament_name} · ${match.round_name||match.stage}`;$('#portal-match-title').textContent=`${match.team_a_name||'TBD'} vs ${match.team_b_name||'TBD'}`;$('#portal-match-modal').classList.remove('hidden');$('#portal-match-body').innerHTML='<div class="ops-empty" style="height:260px">Loading team operations…</div>';try{const [results,checkins,messages,games]=await Promise.all([api(`/api/matches/${matchId}/results`),api(`/api/matches/${matchId}/checkin`),api(`/api/matches/${matchId}/messages`),api(`/api/matches/${matchId}/games`)]);renderMatch(match,results,checkins.checkins,messages.messages,games);}catch(error){$('#portal-match-body').innerHTML=`<div class="ops-empty" style="height:260px">${escapeHtml(error.message)}</div>`;}}
function renderMatch(match,resultData,checkins,messages,gameData){
  const own=myTeamForMatch(match);
  const isCaptain=Boolean(own?.my_is_captain)||own?.my_member_role==='captain';
  const isChecked=checkins.some(item=>item.actor_type==='team'&&Number(item.actor_id)===own?.id);
  const required=isCaptain&&(resultData.requiredTeams||[]).includes(own?.id);
  const hasGameFlow=Array.isArray(gameData.games)&&gameData.games.length>0;
  const workflow=hasGameFlow?renderCaptainGameFlow(match,gameData,own,isCaptain):renderResultActions(match,resultData,own,required,isCaptain);
  $('#portal-match-body').innerHTML=`<div class="ops-match-modal-grid portal-match-operations-grid"><section class="ops-match-settings"><div class="ops-fixed-start"><b>Start time</b><span>${escapeHtml(formatDate(match.effective_scheduled_at))}</span><small>Displayed in your browser's local timezone.</small></div><div class="ops-current-result"><b>${escapeHtml(own?.name||'Your team')}</b><div>${escapeHtml(match.team_a_name||'TBD')} ${match.score_a??0} — ${match.score_b??0} ${escapeHtml(match.team_b_name||'TBD')}</div><div class="ops-list-meta">${escapeHtml(t('portalRoleMatchBo',{role:statusLabel(own?.my_member_role||'player'),status:statusLabel(match.match_status),bestOf:match.best_of}))}</div></div><div class="ops-toolbar">${isCaptain?`<button class="btn ${isChecked?'btn-ghost':'btn-primary'} btn-sm" id="captain-checkin">${isChecked?'✓ CHECKED IN':'CHECK IN TEAM'}</button>`:''}<button class="btn btn-primary btn-sm" id="captain-open-draft">OPEN DRAFT ROOM</button>${match.stream_url?'<button class="btn btn-ghost btn-sm" id="captain-open-stream">OPEN EXTERNAL STREAM ↗</button>':''}</div>${workflow}</section><section class="ops-match-chat-panel"><div class="ops-chat-header"><div><b>MATCH CHAT</b><small>Captains, Host, linked players and assigned referee.</small></div><button class="btn btn-ghost btn-xs" id="captain-refresh-chat">↻</button></div><div class="ops-chat-messages" id="captain-chat"></div><form class="ops-chat-compose" id="captain-chat-form"><input id="captain-chat-input" maxlength="1000" placeholder="Message Host or opponent…"><input id="captain-chat-file" type="file" accept="image/*,.pdf,.txt"><button class="btn btn-primary btn-sm">SEND</button></form></section></div>`;
  $('#captain-checkin')?.addEventListener('click',async()=>{try{await api(`/api/matches/${match.id}/checkin`,{method:'POST',body:{}});toast('Team checked in.');await openMatch(match.id);}catch(error){toast(error.message,true);}});
  $('#captain-open-draft').addEventListener('click',async()=>{try{const payload=await api(`/api/matches/${match.id}/draft-room/access`);openExternal(payload.url);}catch(error){toast(error.message,true);}});
  $('#captain-open-stream')?.addEventListener('click',()=>openExternal(match.stream_url));
  if(hasGameFlow)bindCaptainGameFlow(match,gameData,own,isCaptain);else if(isCaptain)bindResultActions(match,resultData,own);
  $('#captain-refresh-chat').addEventListener('click',()=>refreshChat(match.id));
  $('#captain-chat-form').addEventListener('submit',event=>sendChat(event,match.id));
  messages.forEach(appendChat);
}
function renderCaptainGameFlow(match,gameData,own,isCaptain){
  const games=Array.isArray(gameData.games)?gameData.games:[];
  const current=Number(gameData.currentGameNumber||match.current_game_number||1);
  const game=games.find(item=>Number(item.game_number)===current)||games.at(-1)||{};
  const reportedWinner=Number(game.reported_winner_team_id)===Number(match.team_a_id)?match.team_a_name:Number(game.reported_winner_team_id)===Number(match.team_b_id)?match.team_b_name:'';
  const history=games.map(item=>{const winner=Number(item.winner_team_id)===Number(match.team_a_id)?match.team_a_name:Number(item.winner_team_id)===Number(match.team_b_id)?match.team_b_name:Number(item.reported_winner_team_id)===Number(match.team_a_id)?`${match.team_a_name} · pending`:Number(item.reported_winner_team_id)===Number(match.team_b_id)?`${match.team_b_name} · pending`:'—';const label=item.status==='completed'?'CONFIRMED':item.result_status==='disputed'?'DISPUTED':item.result_status==='awaiting_confirmation'?'WAITING CONFIRMATION':item.status==='draft_complete'?'READY TO REPORT':'DRAFT NOT FINISHED';return `<div class="portal-game-row"><span>GAME ${item.game_number}</span><b>${escapeHtml(label)}</b><em>${escapeHtml(winner)}</em></div>`;}).join('');
  if(match.result_status==='final'||gameData.seriesComplete)return `<section class="ops-result-panel portal-game-flow"><h3>Series Complete</h3><div class="ops-result-warning">${escapeHtml(t('seriesCompleteVerifiedDesc'))}</div><div class="portal-result-summary"><strong>${escapeHtml(match.team_a_name)} ${gameData.scoreA} — ${gameData.scoreB} ${escapeHtml(match.team_b_name)}</strong></div><div class="portal-game-history">${history}</div></section>`;
  if(!isCaptain)return `<section class="ops-result-panel portal-game-flow"><h3>Game ${current} Result</h3><div class="ops-list-meta">Only the linked Captains can report or confirm a game winner. Players may follow the status here and use Match Chat.</div><div class="portal-game-history">${history}</div></section>`;
  let action='';
  if(game.result_status==='disputed')action=`<div class="ops-dispute">Game ${current} is disputed. The next Draft is paused until staff resolve it.</div><form id="captain-evidence-form" class="ops-toolbar"><input id="captain-evidence-file" type="file" accept="image/*,.pdf,.txt" required><button class="btn btn-primary btn-sm">UPLOAD EVIDENCE</button></form>`;
  else if(game.result_status==='awaiting_confirmation'&&Number(game.reported_by_team_id)===Number(own?.id))action=`<div class="ops-result-warning">You reported <b>${escapeHtml(reportedWinner)}</b> as the Game ${current} winner. Waiting for the opposing Captain.</div>`;
  else if(game.result_status==='awaiting_confirmation')action=`<div class="ops-result-warning">The opposing Captain reported <b>${escapeHtml(reportedWinner)}</b> as the Game ${current} winner.</div><div class="portal-result-actions"><button class="btn btn-primary btn-sm" id="captain-confirm-game">CONFIRM GAME ${current}</button><button class="btn btn-danger btn-sm" id="captain-reject-game">${escapeHtml(t('rejectOpenDispute'))}</button></div>`;
  else if(gameData.draftComplete)action=`<div class="ops-result-warning">${escapeHtml(t('reportGameAfterPlaying',{game:current}))}</div><div class="portal-game-winner-buttons"><button class="btn btn-primary" data-game-winner-side="A">${escapeHtml(match.team_a_name)} WON GAME ${current}</button><button class="btn btn-primary" data-game-winner-side="B">${escapeHtml(match.team_b_name)} WON GAME ${current}</button></div>`;
  else action=`<div class="ops-list-meta">${escapeHtml(t('finishDraftBeforeReport',{game:current}))}</div>`;
  return `<section class="ops-result-panel portal-game-flow"><div class="ops-panel-header ops-section-header"><div><h3>Game-by-Game Result</h3><div class="ops-list-meta">${escapeHtml(t('gameByGameFlowShort'))}</div></div><span class="ops-result-lock">GAME ${current}</span></div><div class="portal-series-score"><span>${escapeHtml(match.team_a_name)} <b>${gameData.scoreA||0}</b></span><strong>FIRST TO ${gameData.winsNeeded||Math.floor(match.best_of/2)+1}</strong><span><b>${gameData.scoreB||0}</b> ${escapeHtml(match.team_b_name)}</span></div>${action}<div class="portal-game-history">${history}</div></section>`;
}
function bindCaptainGameFlow(match,gameData,own,isCaptain){
  if(!isCaptain)return;
  $$('[data-game-winner-side]').forEach(button=>button.addEventListener('click',async()=>{const side=button.dataset.gameWinnerSide;const teamName=side==='A'?match.team_a_name:match.team_b_name;if(!confirm(t('reportGameWinnerConfirm',{team:teamName,game:gameData.currentGameNumber})))return;try{await api(`/api/matches/${match.id}/games/current/report`,{method:'POST',body:{winnerSide:side}});toast('Game result reported. Waiting for the opposing Captain.');await loadPortal({quiet:true});await openMatch(match.id);}catch(error){toast(error.message,true);}}));
  $('#captain-confirm-game')?.addEventListener('click',async()=>{try{const payload=await api(`/api/matches/${match.id}/games/current/confirm`,{method:'POST',body:{decision:'confirm'}});toast(payload.final?'Series finalized.':`Game confirmed. Game ${payload.nextGameNumber} Draft is ready.`);await loadPortal({quiet:true});await openMatch(match.id);}catch(error){toast(error.message,true);}});
  $('#captain-reject-game')?.addEventListener('click',async()=>{const comment=prompt(t('gameIncorrectPrompt'));if(!comment)return;try{await api(`/api/matches/${match.id}/games/current/confirm`,{method:'POST',body:{decision:'reject',comment}});toast('Game dispute opened.');await loadPortal({quiet:true});await openMatch(match.id);}catch(error){toast(error.message,true);}});
  $('#captain-evidence-form')?.addEventListener('submit',async event=>{event.preventDefault();const file=$('#captain-evidence-file').files[0];if(!file)return;try{await api(`/api/matches/${match.id}/files`,{method:'POST',body:{purpose:'evidence',originalName:file.name,mimeType:file.type||'application/octet-stream',dataBase64:await readFileBase64(file)}});toast('Evidence uploaded for staff review.');$('#captain-evidence-file').value='';}catch(error){toast(error.message,true);}});
}
function renderResultActions(match,data,own,required,isCaptain=true){
  const current=data.currentSubmission;
  if(!isCaptain)return `<div class="ops-result-panel"><h3>Result Access</h3><div class="ops-list-meta">You can view the match, enter the Draft Room and use Match Chat. Only the linked Captain can check in, submit or verify results.</div></div>`;
  if(match.result_status==='final'){
    const winner=Number(match.winner_team_id)===Number(match.team_a_id)?match.team_a_name:match.team_b_name;
    return `<div class="ops-result-panel"><h3>Final Result</h3><div class="portal-result-summary"><span class="ops-result-lock">VERIFIED & ADVANCED</span><br><strong>${escapeHtml(winner||'Winner')}</strong><br>${escapeHtml(match.team_a_name)} <b>${match.score_a}</b> — <b>${match.score_b}</b> ${escapeHtml(match.team_b_name)}<br><span class="ops-list-meta">Only the Host or Head Referee can undo this result within the correction window and before the next match starts.</span></div></div>`;
  }
  if(['disputed','under_review','recommended'].includes(match.result_status))return `<div class="ops-result-panel"><h3>Result Dispute</h3><div class="ops-dispute">The reports did not match or a Captain rejected the score. Upload evidence and continue the discussion in Match Chat while staff review it.</div><form id="captain-evidence-form" class="ops-toolbar" style="margin-top:10px"><input id="captain-evidence-file" type="file" accept="image/*,.pdf,.txt" required><button class="btn btn-primary btn-sm">UPLOAD EVIDENCE</button></form></div>`;
  const submittedBy=current?.submitted_by_team_id===match.team_a_id?match.team_a_name:current?.submitted_by_team_id===match.team_b_id?match.team_b_name:current?.source_type;
  return `<div class="ops-result-panel"><h3>Result Verification</h3><div class="ops-result-warning">A submitted score does not move a team forward by itself. The required Captain must verify it; a different score or rejection opens a dispute.</div>${current?`<div class="portal-result-summary">Proposed: <b>${escapeHtml(match.team_a_name)} ${current.score_a} — ${current.score_b} ${escapeHtml(match.team_b_name)}</b><br><span class="ops-list-meta">Submitted by ${escapeHtml(submittedBy||'unknown')}. ${required?'Your verification is required.':'Waiting for the other required Captain.'}</span></div>`:'<div class="ops-list-meta">No result has been submitted yet.</div>'}${required?`<div class="portal-result-actions"><button class="btn btn-primary btn-sm" id="captain-confirm-result">CONFIRM THIS SCORE</button><button class="btn btn-danger btn-sm" id="captain-reject-result">${escapeHtml(t('rejectOpenDispute'))}</button></div>`:''}<form id="captain-submit-result" class="ops-result-form"><label>${escapeHtml(match.team_a_name||'Team A')} score<input id="captain-score-a" type="number" min="0" value="${current?.score_a??0}" required></label><label>${escapeHtml(match.team_b_name||'Team B')} score<input id="captain-score-b" type="number" min="0" value="${current?.score_b??0}" required></label><label class="ops-span-2">Note<input id="captain-result-note" placeholder="Optional note"></label><button class="btn btn-primary btn-sm ops-span-2">SUBMIT MY TEAM'S SCORE</button></form></div>`;
}
function bindResultActions(match,data,own){$('#captain-submit-result')?.addEventListener('submit',async event=>{event.preventDefault();try{await api(`/api/matches/${match.id}/results/submit`,{method:'POST',body:{scoreA:Number($('#captain-score-a').value),scoreB:Number($('#captain-score-b').value),note:$('#captain-result-note').value,sourceType:'team',teamId:own.id}});toast('Result submitted.');await loadPortal({quiet:true});await openMatch(match.id);}catch(error){toast(error.message,true);}});$('#captain-confirm-result')?.addEventListener('click',async()=>{try{await api(`/api/matches/${match.id}/results/confirm`,{method:'POST',body:{decision:'confirm'}});toast('Result confirmed.');await loadPortal({quiet:true});await openMatch(match.id);}catch(error){toast(error.message,true);}});$('#captain-reject-result')?.addEventListener('click',async()=>{const comment=prompt('Why is this result incorrect?');if(!comment)return;try{await api(`/api/matches/${match.id}/results/confirm`,{method:'POST',body:{decision:'reject',comment}});toast('Dispute opened.');await loadPortal({quiet:true});await openMatch(match.id);}catch(error){toast(error.message,true);}});$('#captain-evidence-form')?.addEventListener('submit',async event=>{event.preventDefault();const file=$('#captain-evidence-file').files[0];if(!file)return;try{await api(`/api/matches/${match.id}/files`,{method:'POST',body:{purpose:'evidence',originalName:file.name,mimeType:file.type||'application/octet-stream',dataBase64:await readFileBase64(file)}});toast('Evidence uploaded for staff review.');$('#captain-evidence-file').value='';}catch(error){toast(error.message,true);}});}
async function refreshChat(matchId){try{const payload=await api(`/api/matches/${matchId}/messages`);const container=$('#captain-chat');if(container){container.innerHTML='';payload.messages.forEach(appendChat);}}catch(error){toast(error.message,true);}}
function appendChat(message){const container=$('#captain-chat');if(!container||container.querySelector(`[data-message-id="${message.id}"]`))return;const item=document.createElement('div');item.className=`ops-chat-message ${message.message_type==='system'?'system':''} ${message.pinned?'pinned':''}`;item.dataset.messageId=message.id;item.innerHTML=`<div class="ops-chat-message-head"><b>${escapeHtml(message.sender_name||message.sender_role||'Unknown')}</b><span>${formatDate(message.created_at)}${message.edited_at?' · edited':''}</span></div><div>${escapeHtml(message.deleted_at?'[deleted]':message.message||'')}</div>${message.file_id?`<button type="button" class="ops-file-link" data-file-id="${message.file_id}" data-file-name="${escapeHtml(message.file_name||'Attachment')}">📎 ${escapeHtml(message.file_name||'Attachment')}</button>`:''}`;container.appendChild(item);item.querySelector('.ops-file-link')?.addEventListener('click',event=>downloadFile(Number(event.currentTarget.dataset.fileId),event.currentTarget.dataset.fileName));container.scrollTop=container.scrollHeight;}
async function sendChat(event,matchId){event.preventDefault();const input=$('#captain-chat-input'),fileInput=$('#captain-chat-file');try{let fileId=null;const file=fileInput.files[0];if(file){const uploaded=await api(`/api/matches/${matchId}/files`,{method:'POST',body:{purpose:'chat_attachment',originalName:file.name,mimeType:file.type||'application/octet-stream',dataBase64:await readFileBase64(file)}});fileId=uploaded.file.id;}const message=input.value.trim();if(!message&&!fileId)return;await api(`/api/matches/${matchId}/messages`,{method:'POST',body:{message,fileId}});input.value='';fileInput.value='';await refreshChat(matchId);}catch(error){toast(error.message,true);}}


function bindGlobalErrorBoundary(){
  if(window.__gekishinErrorBoundaryBound)return;
  window.__gekishinErrorBoundaryBound=true;
  window.addEventListener('unhandledrejection',event=>{
    event.preventDefault();
    const message=event.reason?.message||'An unexpected operation failed.';
    console.error(event.reason);
    toast(message,true);
  });
  window.addEventListener('error',event=>{
    if(!event.error)return;
    console.error(event.error);
    toast(event.error.message||'An unexpected interface error occurred.',true);
  });
}

bindGlobalErrorBoundary();
bootstrap();
