import { canonicalDiscordInvite, renderPublicEventDescription } from './public-event-content.js';
import { t } from './i18n.js';

const $=selector=>document.querySelector(selector);
const state={payload:null,search:'',zoom:1};
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function label(value){return String(value||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());}
function formatDate(value){if(!value)return 'Start time not announced';const date=new Date(value);return Number.isNaN(date.getTime())?String(value):date.toLocaleString();}
async function load(){const slug=new URLSearchParams(location.search).get('slug');if(!slug)return fail('Missing tournament slug.');try{const response=await fetch(`/api/public/tournaments/${encodeURIComponent(slug)}`);const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||`Request failed (${response.status})`);state.payload=payload;render();}catch(error){fail(error.message);}}
function fail(message){$('#public-loading').classList.add('hidden');$('#public-content').classList.add('hidden');$('#public-error').textContent=message;$('#public-error').classList.remove('hidden');}
function render(){const {tournament}=state.payload;document.title=`${tournament.name} — Public Bracket`;$('#public-loading').classList.add('hidden');$('#public-content').classList.remove('hidden');$('#public-name').textContent=tournament.name;$('#public-status').textContent=label(tournament.status);$('#public-description').innerHTML=renderPublicEventDescription(tournament.description);$('#public-time').textContent=`Tournament start: ${formatDate(tournament.start_at)} · ${tournament.timezone}`;$('#public-source').innerHTML=tournament.source_url?`<a class="ops-live-badge" href="${escapeHtml(tournament.source_url)}" target="_blank" rel="noopener noreferrer">SOURCE: ${escapeHtml((tournament.source_platform||'external').toUpperCase())} ↗</a>`:'';const joinable=!['completed','finalized','archived','cancelled'].includes(String(tournament.status||'').toLowerCase());$('#public-stream').innerHTML=`${joinable?`<a class="btn btn-primary" href="/join-tournament.html?slug=${encodeURIComponent(tournament.slug)}">JOIN / LINK ACCOUNT</a>`:''}${tournament.public_stream_url?`<a class="btn btn-ghost" style="margin-left:8px" href="${escapeHtml(tournament.public_stream_url)}" target="_blank" rel="noopener noreferrer">OPEN ${escapeHtml(tournament.public_stream_platform||'STREAM')} ↗</a><div class="ops-list-meta" style="margin-top:8px">The stream opens directly on the external platform.</div>`:'<div class="ops-list-meta" style="margin-top:8px">No external stream link is active.</div>'}`;renderGroups();renderBracket();$('#public-search').addEventListener('input',event=>{state.search=event.target.value.toLowerCase();renderBracket();});$('#public-fit').addEventListener('click',()=>{state.zoom=.8;renderBracket();});$('#public-fullscreen').addEventListener('click',()=>$('#public-bracket-viewport').requestFullscreen());}
function renderGroups(){const groups=state.payload.groupStandings||[];const container=$('#public-groups');if(!groups.length){container.innerHTML='';return;}container.innerHTML=`<div class="ops-section"><div class="ops-section-header"><div><h3>Group Standings</h3><div class="ops-list-meta">Standings update after results become Final.</div></div></div><div class="ops-group-grid">${groups.map(group=>`<article class="ops-group-panel"><h3>GROUP ${escapeHtml(group.group)}</h3><div class="ops-standing-table">${group.standings.map(row=>`<div class="ops-standing-row ${row.rank<=2?'qualifying':''}"><b>${row.rank}</b><span>${escapeHtml(row.tag||row.name)}</span><span>${row.wins}-${row.losses}</span><span>${row.gameDiff>=0?'+':''}${row.gameDiff}</span><span>${row.overrideActive?'OVERRIDE':''}</span></div>`).join('')}</div></article>`).join('')}</div></div>`;}
function publicMatchCard(match){const hay=`${match.teamA?.name||''} ${match.teamB?.name||''}`.toLowerCase();const hidden=state.search&&!hay.includes(state.search);if(hidden)return '';return `<article class="ops-match-card ${match.resultStatus==='final'?'final':''}"><div class="ops-match-id">#${match.position} · ${escapeHtml(label(match.matchStatus))}</div><div class="ops-match-team ${match.winnerTeamId===match.teamA?.id?'winner':''}"><span>${escapeHtml(match.teamA?.tag||match.teamA?.name||'TBD')}</span><b>${match.scoreA??'—'}</b></div><div class="ops-match-team ${match.winnerTeamId===match.teamB?.id?'winner':''}"><span>${escapeHtml(match.teamB?.tag||match.teamB?.name||'TBD')}</span><b>${match.scoreB??'—'}</b></div><div class="ops-match-footer"><span>BO${match.bestOf} · ${escapeHtml(label(match.resultStatus))}</span><span>${escapeHtml(formatDate(match.effectiveScheduledAt))}</span>${match.streamUrl?`<a class="ops-live-badge" href="${escapeHtml(match.streamUrl)}" target="_blank" rel="noopener noreferrer">STREAM ↗</a>`:''}</div>${match.publicNotes?`<div class="ops-list-meta" style="margin-top:7px">${escapeHtml(match.publicNotes)}</div>`:''}</article>`;}
function renderBracket(){const matches=(state.payload.matches||[]).filter(match=>match.stage!=='group');const rounds=[...new Set(matches.map(match=>match.roundNo))].sort((a,b)=>a-b);$('#public-bracket').style.transform=`scale(${state.zoom})`;$('#public-bracket').innerHTML=rounds.length?rounds.map(round=>{const rows=matches.filter(match=>match.roundNo===round);return `<section class="ops-round"><div class="ops-round-header"><div class="ops-round-title">${escapeHtml(rows[0]?.roundName||`Round ${round}`)}</div></div><div class="ops-round-matches">${rows.map(publicMatchCard).join('')||'<div class="ops-list-meta">No matching teams.</div>'}</div></section>`;}).join(''):'<div class="portal-empty">The bracket has not been generated yet.</div>';}
function renderDedicatedDiscordInvite(){const container=$('#public-discord');if(!container)return;const invite=canonicalDiscordInvite(state.payload?.tournament?.discord_url);container.innerHTML=invite?`<a class="btn btn-discord" href="${escapeHtml(invite)}" target="_blank" rel="noopener noreferrer nofollow">${escapeHtml(t('joinDiscordServer'))}</a>`:'';}
load().then(renderDedicatedDiscordInvite);
