// Generated by scripts/build-web-trailers.mjs; source media stays untouched.
export const WEB_TRAILERS = Object.freeze({
  "0001": {
    "src": "assets/trailers/web/0001-800b74cce3ab.mp4",
    "sourceHash": "b2a326f090c45abb23b0d5b42fb55827fd775cbfee788ba8635a0b82e81dd8b1",
    "sourceBytes": 5963860,
    "bytes": 2524424
  },
  "0002": {
    "src": "assets/trailers/web/0002-bba098c2c32c.mp4",
    "sourceHash": "c04d02a1a99f159bb33d48dfeb0abc21ae02d56de8abd3d19cef62656eda7a06",
    "sourceBytes": 6606598,
    "bytes": 2585885
  },
  "0003": {
    "src": "assets/trailers/web/0003-5634264dd3f4.mp4",
    "sourceHash": "d7638ad188c7547b472aba52ac19a754496ae5d4e69f9f5c1532a5d12b74953e",
    "sourceBytes": 6076746,
    "bytes": 2633475
  },
  "0004": {
    "src": "assets/trailers/web/0004-2d05a2a0e7dd.mp4",
    "sourceHash": "ef1195a13d3d0132e637b2eaf63543f79c3bba6e02839c34fa285c238dc1606a",
    "sourceBytes": 6370671,
    "bytes": 2587295
  },
  "0005": {
    "src": "assets/trailers/web/0005-b3444b5732e6.mp4",
    "sourceHash": "5164626398c2b1f8acdca4113768f1d1b9bd4c4020c216afc6d85c95c5ee9ab5",
    "sourceBytes": 6443406,
    "bytes": 2612573
  },
  "0006": {
    "src": "assets/trailers/web/0006-8f91666812e3.mp4",
    "sourceHash": "8b54dccedc5d381446553dcfa144f88499e274a2975c71f40146079754d19abd",
    "sourceBytes": 5898505,
    "bytes": 2648911
  },
  "0007": {
    "src": "assets/trailers/web/0007-557df07282dd.mp4",
    "sourceHash": "747fe69f32078df3b6d7fe66e29302e8f81a828c270684db7dabfa76c3b01a0b",
    "sourceBytes": 6348619,
    "bytes": 2673854
  },
  "0008": {
    "src": "assets/trailers/web/0008-81a42a33598f.mp4",
    "sourceHash": "a855c1074063df0076445b7401f687f56966dcfb15d39757a45895b0b96e329e",
    "sourceBytes": 6303828,
    "bytes": 2589435
  },
  "0009": {
    "src": "assets/trailers/web/0009-4ab83405961e.mp4",
    "sourceHash": "99261c2d5ef7d6c9c8433def01f5dcaa391e1241df183344ebdbf80cfe8c49d0",
    "sourceBytes": 6028146,
    "bytes": 2679401
  },
  "0010": {
    "src": "assets/trailers/web/0010-f449ad3c8a24.mp4",
    "sourceHash": "7402a8b68418ae5dcccd86510a27adc0fec179a617507f580b331816b66c35bd",
    "sourceBytes": 5894428,
    "bytes": 2571813
  },
  "0011": {
    "src": "assets/trailers/web/0011-d0ebda0cef93.mp4",
    "sourceHash": "71e0e3df94683e7c7fec1694be8a7e3448003625026c71d1eed78e03d71a47f0",
    "sourceBytes": 5986152,
    "bytes": 2539171
  },
  "0012": {
    "src": "assets/trailers/web/0012-ab75d3decb0b.mp4",
    "sourceHash": "991b15b513bf4d2b37d775c32e50450e79adb9c42c03e4c0e225631278d0e3a7",
    "sourceBytes": 6009833,
    "bytes": 2637621
  },
  "0013": {
    "src": "assets/trailers/web/0013-919e4cbaafc2.mp4",
    "sourceHash": "18d2187000a1c916eba72e52263a7120a99bd78ef25e084ea0306b9a5ea9d570",
    "sourceBytes": 6383351,
    "bytes": 2593922
  },
  "0014": {
    "src": "assets/trailers/web/0014-4c9869ccd381.mp4",
    "sourceHash": "003cf4c2af5a5b240a2f267fee56d5a15d385e7cee4a1ea37788d91fd789a8ca",
    "sourceBytes": 5875578,
    "bytes": 2615631
  },
  "0015": {
    "src": "assets/trailers/web/0015-459b145555aa.mp4",
    "sourceHash": "6f7858b1e07c6c5511ef19e62032d5735310502eaf72c10b850417c5efd7a4fd",
    "sourceBytes": 5874824,
    "bytes": 2625835
  },
  "0016": {
    "src": "assets/trailers/web/0016-905658f67fc8.mp4",
    "sourceHash": "628d78ca4d0642d0ea9a8319b3968a84815eaa3e79697ac51007fe0aac0aa23d",
    "sourceBytes": 6353351,
    "bytes": 2620882
  },
  "0017": {
    "src": "assets/trailers/web/0017-5ce70d0d27bb.mp4",
    "sourceHash": "18bb383a8e63f263383a7ed34bc4ec22ab12be5d83c410dfbfa1a059647fe63d",
    "sourceBytes": 5699120,
    "bytes": 2503358
  },
  "0018": {
    "src": "assets/trailers/web/0018-abccb61b2dc9.mp4",
    "sourceHash": "59739a8dbfdff48e48009bb857dacba71c76f681fb9dbb0f8427cc7e9c1e2389",
    "sourceBytes": 6425157,
    "bytes": 2630279
  },
  "0019": {
    "src": "assets/trailers/web/0019-bd8301af4dbc.mp4",
    "sourceHash": "2e2221851e097a881e4825b973f94699ff21b27b7e6b7623cbfa9ea04e972181",
    "sourceBytes": 6158017,
    "bytes": 2506825
  },
  "0020": {
    "src": "assets/trailers/web/0020-069b35afce80.mp4",
    "sourceHash": "2933049399cef8b901f5b81eb848c098685fb1e69dc4b06ea00139e152c25370",
    "sourceBytes": 6228427,
    "bytes": 2447731
  },
  "0021": {
    "src": "assets/trailers/web/0021-dd5682f0aebb.mp4",
    "sourceHash": "b32fc897e1992f70450efc9e92ba7ca3a4d84c5f91a640e8d5f0bd82500f059a",
    "sourceBytes": 6005780,
    "bytes": 2633880
  },
  "0022": {
    "src": "assets/trailers/web/0022-516b30c1cdbd.mp4",
    "sourceHash": "3f50598790f31067f0aec85b0bd3370eb330393d59bd65e85fc9b99e9336ac68",
    "sourceBytes": 5715341,
    "bytes": 2618800
  },
  "0023": {
    "src": "assets/trailers/web/0023-292de01df5e9.mp4",
    "sourceHash": "d098fb3621f555ef96be640215f70dfb9ff945059ef40db9c8aed3bf10c23b35",
    "sourceBytes": 6305686,
    "bytes": 2642550
  },
  "0024": {
    "src": "assets/trailers/web/0024-2d90411fed9c.mp4",
    "sourceHash": "5352ee7dbef2a551fbe026344f06efd51bca536635401c36e2006b1c4d94fbb6",
    "sourceBytes": 6571883,
    "bytes": 2720194
  },
  "0025": {
    "src": "assets/trailers/web/0025-c9f77e5ecbdd.mp4",
    "sourceHash": "0918c5a6221f9705c1c17e03b2339d99c7b93c9f807ca2a875cb023960f134b7",
    "sourceBytes": 6083244,
    "bytes": 2575577
  },
  "0026": {
    "src": "assets/trailers/web/0026-8c6b93dbfa75.mp4",
    "sourceHash": "84abf1d4de69efa3bb66ddf4ab4f88f03df027b52a33a5cea3aaec6e2cf54e39",
    "sourceBytes": 6183193,
    "bytes": 2629565
  },
  "0027": {
    "src": "assets/trailers/web/0027-19e20f18e0cf.mp4",
    "sourceHash": "c5c7c5a7e43abbeead313c0eaa1dfab2fa9d10a53126b0411c6be2dbea2337d9",
    "sourceBytes": 6176493,
    "bytes": 2661533
  },
  "0028": {
    "src": "assets/trailers/web/0028-68d46b02afbc.mp4",
    "sourceHash": "5a041edffe57c0dff1a07c125dd032e1d02b018026411cbdce021aa6ec1973da",
    "sourceBytes": 6447741,
    "bytes": 2598348
  },
  "0029": {
    "src": "assets/trailers/web/0029-7661eb7fe715.mp4",
    "sourceHash": "f9ac7ed129edd85dbc46426a035caa95b72282f43ebaa27182a3e16836074a2d",
    "sourceBytes": 5955959,
    "bytes": 2585399
  },
  "0030": {
    "src": "assets/trailers/web/0030-7370cb562eed.mp4",
    "sourceHash": "8f521fb1a2c4be9d244b6b00cae6cb6264f7b976866bcf7c9a8fee312e26345c",
    "sourceBytes": 4266047,
    "bytes": 2526910
  },
  "0031": {
    "src": "assets/trailers/web/0031-906fbc9d9cf2.mp4",
    "sourceHash": "5a25f618a9fdd6ed4d1479bd3026ad0bcf5d9ad2ea67089f69e2049271987597",
    "sourceBytes": 6112287,
    "bytes": 2685030
  },
  "0032": {
    "src": "assets/trailers/web/0032-878afe27a1f3.mp4",
    "sourceHash": "4ba584cd1e7c2a802bc63ddab5b0e19e7809c7befb3be2e5a83d999d6ff48834",
    "sourceBytes": 6056227,
    "bytes": 2530256
  },
  "0033": {
    "src": "assets/trailers/web/0033-1b389d4b2f63.mp4",
    "sourceHash": "a8305d40daffb208161a3d088432d2d03fa3cb4e879abcacf654f8dcf7694a26",
    "sourceBytes": 6321203,
    "bytes": 2636437
  },
  "0034": {
    "src": "assets/trailers/web/0034-f0d3c60cc61f.mp4",
    "sourceHash": "38f5f47fbecb2f23fd4c893f904c1bdd12c8472a874c7fc4cd7832e2287fafb1",
    "sourceBytes": 6277101,
    "bytes": 2609520
  },
  "0035": {
    "src": "assets/trailers/web/0035-21d799e9d777.mp4",
    "sourceHash": "95f04ba4f093d02f64538e2207f468d519b4e625092eb9a2bb4890dbcb44850b",
    "sourceBytes": 6115792,
    "bytes": 2657361
  },
  "0036": {
    "src": "assets/trailers/web/0036-937d14be0d3c.mp4",
    "sourceHash": "9bf92c1f14582c68849907e49ca8e21d6a02977c9cfb689f9b72b63a8a3f70a9",
    "sourceBytes": 6706887,
    "bytes": 2525239
  },
  "0037": {
    "src": "assets/trailers/web/0037-2c387206d8ae.mp4",
    "sourceHash": "90b5dc0c45401664d15a6061bed4ae0b2525a8216b76abcfccd9f6407719ba64",
    "sourceBytes": 6074476,
    "bytes": 2668543
  },
  "0038": {
    "src": "assets/trailers/web/0038-04efafa9afee.mp4",
    "sourceHash": "5de54573802f1f98f1ac3c85cef839cb0b5f29252b30fc3c4a5090f55ad9b489",
    "sourceBytes": 6329416,
    "bytes": 2682097
  },
  "0039": {
    "src": "assets/trailers/web/0039-505e4c9c7cf9.mp4",
    "sourceHash": "56a886b726beff192b9ff2fdf2247c05b53ff71cbfe335c663ec18b19aa75312",
    "sourceBytes": 5853292,
    "bytes": 2524297
  },
  "0040": {
    "src": "assets/trailers/web/0040-914e6f3d152e.mp4",
    "sourceHash": "d0e423342075f8c20b0b3076851c5b0e5a6951fe3823999ac17bf655a633ec9b",
    "sourceBytes": 9288043,
    "bytes": 3638551
  },
  "0041": {
    "src": "assets/trailers/web/0041-f56579ef4fb1.mp4",
    "sourceHash": "d46fa6b3b4fdeb012d3c5663fee4557ac6b88ccba95028384911e8960d00e961",
    "sourceBytes": 6598830,
    "bytes": 2695033
  }
});
export const WEB_TRAILER_POSTERS = Object.freeze({
  "0001": {
    "src": "assets/trailers/web/0001-poster-0ce0cd280463.webp",
    "sourceSrc": "assets/trailers/0001.png",
    "sourceHash": "5b9b74c157801dc31ea9a91a5008fd0c0b4c5ea988f62e0149f45aa05d47ed71",
    "sourceBytes": 949449,
    "bytes": 239650
  },
  "0003": {
    "src": "assets/trailers/web/0003-poster-52b6e3f578bd.webp",
    "sourceSrc": "assets/trailers/0003.png",
    "sourceHash": "992b515580e20833c3aadefacf6070e0d388e00f4a41b360bbb87aa5423fec0f",
    "sourceBytes": 836307,
    "bytes": 221780
  },
  "0005": {
    "src": "assets/trailers/web/0005-poster-5394c0d683cd.webp",
    "sourceSrc": "assets/trailers/0005.png",
    "sourceHash": "50df52d0ac651df6e81fbece5f3cccaaca938771f8232b5983b6d045d0091e87",
    "sourceBytes": 1062941,
    "bytes": 237892
  },
  "0006": {
    "src": "assets/trailers/web/0006-poster-ff0a017d7928.webp",
    "sourceSrc": "assets/trailers/0006.png",
    "sourceHash": "2b37b912d4d79c18483625cf07d9f2bc72ed129eb72d713d2f72069c6db0ca80",
    "sourceBytes": 1162223,
    "bytes": 219458
  },
  "0007": {
    "src": "assets/trailers/web/0007-poster-9970fac90e1b.webp",
    "sourceSrc": "assets/trailers/0007.png",
    "sourceHash": "c9641f25786dd9e85d8270eaa1374a5243921f2a6c8a0354e08a3a6d0412c644",
    "sourceBytes": 719005,
    "bytes": 184178
  },
  "0008": {
    "src": "assets/trailers/web/0008-poster-5bd855342653.webp",
    "sourceSrc": "assets/trailers/0008.png",
    "sourceHash": "a70cf3ab1d1424b1b3da208b1115b643dd2984361c787811ff404b532216eb47",
    "sourceBytes": 1340947,
    "bytes": 212574
  },
  "0009": {
    "src": "assets/trailers/web/0009-poster-925513ce73f9.webp",
    "sourceSrc": "assets/trailers/0009.png",
    "sourceHash": "31f7cd260bd0a8135182b194a979e98c98fff6f3f1fd909e5b21ad6801a83b49",
    "sourceBytes": 769563,
    "bytes": 193848
  },
  "0010": {
    "src": "assets/trailers/web/0010-poster-12f6860a7aba.webp",
    "sourceSrc": "assets/trailers/0010.png",
    "sourceHash": "00f8668e7f3384d0b7709abe0333aa0282bbd965930567a4e2a4b2b71aca40ad",
    "sourceBytes": 1019703,
    "bytes": 233326
  },
  "0011": {
    "src": "assets/trailers/web/0011-poster-e94b3ba25412.webp",
    "sourceSrc": "assets/trailers/0011.png",
    "sourceHash": "77fca19e6ac43a8d5639b83fda9deb883e24235275038b107c0d7f1d043e3988",
    "sourceBytes": 980478,
    "bytes": 187800
  },
  "0012": {
    "src": "assets/trailers/web/0012-poster-21eb395703fb.webp",
    "sourceSrc": "assets/trailers/0012.png",
    "sourceHash": "a2ab4541e014c755b71c85e31cad8ed9efd427f33415807d5b0f8a3933085af2",
    "sourceBytes": 1031180,
    "bytes": 231928
  },
  "0013": {
    "src": "assets/trailers/web/0013-poster-b7c31f2e2457.webp",
    "sourceSrc": "assets/trailers/0013.png",
    "sourceHash": "640a9d20b9d7061f826ace657717a4b6d2deee0614dcc83b697aebb9391d6cdc",
    "sourceBytes": 913145,
    "bytes": 227926
  },
  "0014": {
    "src": "assets/trailers/web/0014-poster-07f76c3ab4d4.webp",
    "sourceSrc": "assets/trailers/0014.png",
    "sourceHash": "ab04b83e0eb25ed6d01acdd32fa425dcc5689a9ff833fc94aebb8fb8605fa30b",
    "sourceBytes": 719330,
    "bytes": 181414
  },
  "0015": {
    "src": "assets/trailers/web/0015-poster-44286ed9e258.webp",
    "sourceSrc": "assets/trailers/0015.png",
    "sourceHash": "6d1f1f341867c8d7ecf0502be53a9c95e02347f1cd56da239feb0d4c44580c9a",
    "sourceBytes": 975935,
    "bytes": 200324
  },
  "0016": {
    "src": "assets/trailers/web/0016-poster-093dbe4a71d1.webp",
    "sourceSrc": "assets/trailers/0016.png",
    "sourceHash": "da514fe6df721c3d22e5d1ca6a62702ace1f980192be39780d9ee7a195f86ae2",
    "sourceBytes": 907970,
    "bytes": 210342
  },
  "0017": {
    "src": "assets/trailers/web/0017-poster-ba14e85ee2f1.webp",
    "sourceSrc": "assets/trailers/0017.png",
    "sourceHash": "e7963b6036d3117a86df41ffee9dfa6e85edfc140cdd826aa1ac92c41ba2c3f6",
    "sourceBytes": 920814,
    "bytes": 229232
  },
  "0018": {
    "src": "assets/trailers/web/0018-poster-fc60a452424d.webp",
    "sourceSrc": "assets/trailers/0018.png",
    "sourceHash": "9d918a198f90d79b97921d802554dbc7e562b67b49d2a6e45752ad7cce79e8b1",
    "sourceBytes": 1060300,
    "bytes": 215524
  },
  "0019": {
    "src": "assets/trailers/web/0019-poster-1308aa21b2ed.webp",
    "sourceSrc": "assets/trailers/0019.png",
    "sourceHash": "ad9c1b445cfe3c58a67a5e0e38dd3cf4fb2d6690c4fd6f8c85896257777d4c43",
    "sourceBytes": 1082711,
    "bytes": 200904
  },
  "0020": {
    "src": "assets/trailers/web/0020-poster-7e01d77c6b3d.webp",
    "sourceSrc": "assets/trailers/0020.png",
    "sourceHash": "f1d76d1efc05bacb6b385ca1f937fbca89ca5ee75df7aa57a133e9c575a7eccd",
    "sourceBytes": 799253,
    "bytes": 176630
  },
  "0021": {
    "src": "assets/trailers/web/0021-poster-0d53a1ab4a80.webp",
    "sourceSrc": "assets/trailers/0021.png",
    "sourceHash": "09807752c4d82954b46033c12bb1c0466bc00971348451e989ac6032874e3ae5",
    "sourceBytes": 940751,
    "bytes": 184298
  },
  "0022": {
    "src": "assets/trailers/web/0022-poster-9a62c0220be0.webp",
    "sourceSrc": "assets/trailers/0022.png",
    "sourceHash": "c0db9dc207012d7343012ac24f9d4a30da4923a4f0a7bad0c30a05c28f07e514",
    "sourceBytes": 1035248,
    "bytes": 253846
  },
  "0023": {
    "src": "assets/trailers/web/0023-poster-4849746c081d.webp",
    "sourceSrc": "assets/trailers/0023.png",
    "sourceHash": "0d19e7c1e325e88d054ee3497b96df87589618fedac14a7ae109a0c8726f8876",
    "sourceBytes": 1490987,
    "bytes": 242666
  },
  "0024": {
    "src": "assets/trailers/web/0024-poster-cf4477d8317d.webp",
    "sourceSrc": "assets/trailers/0024.png",
    "sourceHash": "2e4ce55d91364cf7466091ac5437dbae1daea194f8341fcc4d213e48b2498460",
    "sourceBytes": 868279,
    "bytes": 211898
  },
  "0025": {
    "src": "assets/trailers/web/0025-poster-ba67216ef711.webp",
    "sourceSrc": "assets/trailers/0025.png",
    "sourceHash": "28a0d06eda1e9e09d2262c55a4122078bc5a87a24924d3d9bd0f098c8ad98c6f",
    "sourceBytes": 1009496,
    "bytes": 231224
  },
  "0026": {
    "src": "assets/trailers/web/0026-poster-411bcb93b874.webp",
    "sourceSrc": "assets/trailers/0026.png",
    "sourceHash": "7cd71208688c5266b28025fc3574f4b85fa8a0ac9a7c4f07a32207981201a834",
    "sourceBytes": 1128793,
    "bytes": 226956
  },
  "0027": {
    "src": "assets/trailers/web/0027-poster-46d339ad62cb.webp",
    "sourceSrc": "assets/trailers/0027.png",
    "sourceHash": "cbaccafed04b565d1b7525f6feaa260786175e5de2eda8c15f5920c39b8d0a4b",
    "sourceBytes": 1087460,
    "bytes": 238420
  },
  "0028": {
    "src": "assets/trailers/web/0028-poster-df53116afc09.webp",
    "sourceSrc": "assets/trailers/0028.png",
    "sourceHash": "1e9495a7115af8f97f383e9c1d016b7b73533893d6e2d48e83baeeeb3052a147",
    "sourceBytes": 1027409,
    "bytes": 245150
  },
  "0029": {
    "src": "assets/trailers/web/0029-poster-0e54a02444bf.webp",
    "sourceSrc": "assets/trailers/0029.png",
    "sourceHash": "989b89f991287d2d06aa15e08babd06abf10004f98b65e139efb92da4f81df41",
    "sourceBytes": 1014165,
    "bytes": 245254
  },
  "0030": {
    "src": "assets/trailers/web/0030-poster-8dbfa4626496.webp",
    "sourceSrc": "assets/trailers/0030.png",
    "sourceHash": "dc1d2bcc305592600a88b9b2f587815828d59dc6a864294b4c664d85b0d8081a",
    "sourceBytes": 873960,
    "bytes": 226782
  },
  "0031": {
    "src": "assets/trailers/web/0031-poster-bdc7afebb76e.webp",
    "sourceSrc": "assets/trailers/0031.png",
    "sourceHash": "3c29ab1573ead6a05979e106d58b5d62459e0c05c31a251413452caa32e5fd3e",
    "sourceBytes": 964698,
    "bytes": 235366
  },
  "0032": {
    "src": "assets/trailers/web/0032-poster-ec6495f6e36a.webp",
    "sourceSrc": "assets/trailers/0032.png",
    "sourceHash": "5f5a0bc0b836e6345b77d4b00a59f2fa6b74b7848cc80d58b8492cf9468b4ccb",
    "sourceBytes": 1390054,
    "bytes": 197758
  },
  "0033": {
    "src": "assets/trailers/web/0033-poster-da86bc99c386.webp",
    "sourceSrc": "assets/trailers/0033.png",
    "sourceHash": "06ff16b65ddd718ba52952df149922b263e95ebab53675991f002028a49ff0cf",
    "sourceBytes": 1303367,
    "bytes": 190058
  },
  "0034": {
    "src": "assets/trailers/web/0034-poster-fe5bd192000c.webp",
    "sourceSrc": "assets/trailers/0034.png",
    "sourceHash": "8e8fe7f54a1510fe47abc6b38107c0af0dbe84a2f24fb68f46cfd50e5a591311",
    "sourceBytes": 1271066,
    "bytes": 199630
  },
  "0035": {
    "src": "assets/trailers/web/0035-poster-923d99404731.webp",
    "sourceSrc": "assets/trailers/0035.png",
    "sourceHash": "366c4ec115d02e2a93d58b199c8f5cabef331641eab0931148f62e92a414edc6",
    "sourceBytes": 1043065,
    "bytes": 213530
  },
  "0036": {
    "src": "assets/trailers/web/0036-poster-9f4746b6a419.webp",
    "sourceSrc": "assets/trailers/0036.png",
    "sourceHash": "50985fb4dc90c957c0775aa50de1e5552eae26c6792dc2576ac413e4d2ec23f8",
    "sourceBytes": 1075725,
    "bytes": 225146
  },
  "0037": {
    "src": "assets/trailers/web/0037-poster-39c84a1bdfa2.webp",
    "sourceSrc": "assets/trailers/0037.png",
    "sourceHash": "28f8a4a66ca6e4f578c9488ff422105f8c7232a3ea731b45b27e7a2cd278f9da",
    "sourceBytes": 1093646,
    "bytes": 214424
  },
  "0038": {
    "src": "assets/trailers/web/0038-poster-2f40518889a9.webp",
    "sourceSrc": "assets/trailers/0038.png",
    "sourceHash": "3b6a0e71789e3bc0a86ac49362e125573420bd6bdeb06d506e3623e202f19b46",
    "sourceBytes": 946636,
    "bytes": 220678
  },
  "0039": {
    "src": "assets/trailers/web/0039-poster-e1efc6e6b9eb.webp",
    "sourceSrc": "assets/trailers/0039.png",
    "sourceHash": "7656f77bb8ab65e74d9cb9daa0fd628ccd931725af067d028aee7e5dc6325464",
    "sourceBytes": 858543,
    "bytes": 179528
  },
  "0040": {
    "src": "assets/trailers/web/0040-poster-9f63674c56c1.webp",
    "sourceSrc": "assets/trailers/0040.webp",
    "sourceHash": "a17d6affa2c757d2ada5543e3f05820712937732ff17264a38144da5c2767406",
    "sourceBytes": 8296178,
    "bytes": 180380
  },
  "0041": {
    "src": "assets/trailers/web/0041-poster-26aa205e0a5c.webp",
    "sourceSrc": "assets/trailers/0041.webp",
    "sourceHash": "8c7acfbf277b8b3fc740f8f651b88dc475ee41fe261a81689f0034354cd3292e",
    "sourceBytes": 2364928,
    "bytes": 141312
  }
});
