import assert from 'node:assert/strict';
import { readdir, readFile } from 'node:fs/promises';

const page = await readFile(new URL('../heroes.html', import.meta.url), 'utf8');
const script = await readFile(new URL('../js/heroes-page.js', import.meta.url), 'utf8');
const heroesModule = await readFile(new URL('../js/heroes.js', import.meta.url), 'utf8');
const server = await readFile(new URL('../server.js', import.meta.url), 'utf8');
const rules = await readFile(new URL('../js/draft-rules-form.js', import.meta.url), 'utf8');
const apiScript = await readFile(new URL('../js/api.js', import.meta.url), 'utf8');
const assetFiles = new Set(await readdir(new URL('../assets/divine-cards/', import.meta.url)));
const catalog = JSON.parse(await readFile(new URL('../assets/divine-cards/catalog.json', import.meta.url), 'utf8'));
const catalogFilenames = catalog.map(card => card.filename);

assert.equal(catalog.length, 18, 'The public Divine Card catalog must contain exactly 18 cards.');
assert.equal(new Set(catalog.map(card => card.id)).size, 18, 'Divine Card catalog IDs must be unique.');
assert.equal(new Set(catalogFilenames).size, 18, 'Divine Card catalog filenames must be unique.');
assert.ok(catalogFilenames.every(name => /^[a-z0-9]+(?:-[a-z0-9]+)*\.png$/.test(name)), 'Catalog filenames must be human-readable slugs.');
assert.ok(catalogFilenames.every(name => assetFiles.has(name)), 'Every catalog image must exist in assets/divine-cards.');
assert.ok(!catalogFilenames.some(name => /^000\d/.test(name)), 'The public catalog must not expose legacy ID filenames.');
assert.match(page, /HEROES (?:&|&amp;) DIVINE CARD BUILDS/);
assert.match(page, /data-admin-pane="catalog"/);
assert.match(page, /data-admin-pane="presets"/);
assert.match(page, /data-admin-pane="assign"/);
assert.match(page, /preset-card-inspector/);
assert.match(page, /preset-game-board/);
assert.match(page, /assignment-role-filters/);
assert.match(page, /select-assigned-heroes/);
assert.match(page, /REMOVE FROM SELECTED/);
assert.match(page, /data-assignment-role="Damage"/);
assert.match(page, /Use case \/ matchup/);
assert.match(script, /text\/divine-card-id/);
assert.match(script, /Attack · Defense · Technical/);
assert.match(script, /t\('noteConditions'\)/);
assert.doesNotMatch(script, /catalog-card-id/);
assert.match(script, /heroAssignments/);
assert.match(script, /data-unassign-hero/);
assert.match(script, /updatePresetAssignments/);
assert.match(script, /builderSwaps/);
assert.match(page, /Cards 1–3/);
assert.match(page, /Cards 4–6/);
assert.match(page, /Cards 7–9/);
assert.match(script, /SITUATION CARD/);
assert.match(script, /slot \+ \(priority \* 3\)/);
assert.match(script, /builderSwapOptionsPayload/);
assert.match(script, /builderSituationalSlotsPayload/);
assert.match(script, /situationalSlots/);
assert.match(script, /mergeSavedPreset/);
assert.match(page, /heroes-page\.js\?v=[A-Za-z0-9._-]+/);
assert.match(apiScript, /cache = 'no-store'/);
assert.match(script, /for \(const priority of \[1, 2\]\)/);
assert.match(script, /builderTarget/);
assert.match(script, /swapOptions/);
assert.match(script, /CARD CHANGE RULE/);
assert.match(script, /captureAdminScroll/);
assert.match(script, /restoreAdminScroll/);
assert.match(rules, /previousGridTop/);
assert.match(script, /assignmentRole/);
assert.match(script, /statsPath/);
assert.match(script, /getHeroSkillIconUrls/);
assert.match(heroesModule, /assets\/heroes\/\$\{heroId\}\/skill\/icon_\$\{skillId\}/);
assert.doesNotMatch(heroesModule, /dbg-squadra\.bn-ent\.net/);
assert.match(script, /hero-difficulty-track/);

assert.match(script, /function bindCardTooltips\(\)/);
assert.match(script, /data-card-tooltip/);
assert.match(script, /divine-card-tooltip/);
assert.match(script, /cardPreviewState/);
assert.match(script, /t\('pinned'\)/);
assert.match(script, /pinned:true/);
assert.match(script, /Hover or focus for details/);
assert.doesNotMatch(script, /class="divine-build-effect"/);
assert.doesNotMatch(script, /<article class="divine-library-card[^`]*<p>/s);
assert.match(server, /divineCardAdminRequired/);
assert.match(server, /DIVINE_CARD_ADMIN_EMAIL/);
assert.doesNotMatch(rules, /⟫|◆|◎|⚔|🎲|🪙|🛡|🎬|🎥|⚡/);

console.log('Heroes page, owner-only Divine Card admin and drag/drop build UI checks passed.');

assert.match(script, /topSafe = Math\.max\(24, height \* \.06\)/, 'Hero art must reserve visible space above the head.');
assert.match(script, /heroNameClass/);
assert.match(script, /is-super-saiyan/);
